# Generated by Django 4.1.7 on 2023-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(related_name='polls', to='polls.choice'),
        ),
    ]
