# Generated by Django 4.1.7 on 2023-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_poll_poll_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voices',
            field=models.IntegerField(default=0),
        ),
    ]
