# Generated by Django 4.1.7 on 2023-03-10 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_choice_voices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_voted_by_user', to='polls.poll', verbose_name='Опрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_user', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
        ),
    ]
