# Generated by Django 4.1.7 on 2023-03-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_userpolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolls',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_choice_by_user', to='polls.choice', verbose_name='Выбор'),
        ),
    ]
